// Code generated by mockery. DO NOT EDIT.

package client

import (
	context "context"

	client "github.com/openfga/go-sdk/client"

	mock "github.com/stretchr/testify/mock"

	openfga "github.com/openfga/go-sdk"
)

// MockSdkClientExpandRequestInterface is an autogenerated mock type for the SdkClientExpandRequestInterface type
type MockSdkClientExpandRequestInterface struct {
	mock.Mock
}

type MockSdkClientExpandRequestInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSdkClientExpandRequestInterface) EXPECT() *MockSdkClientExpandRequestInterface_Expecter {
	return &MockSdkClientExpandRequestInterface_Expecter{mock: &_m.Mock}
}

// Body provides a mock function with given fields: body
func (_m *MockSdkClientExpandRequestInterface) Body(body client.ClientExpandRequest) client.SdkClientExpandRequestInterface {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for Body")
	}

	var r0 client.SdkClientExpandRequestInterface
	if rf, ok := ret.Get(0).(func(client.ClientExpandRequest) client.SdkClientExpandRequestInterface); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SdkClientExpandRequestInterface)
		}
	}

	return r0
}

// MockSdkClientExpandRequestInterface_Body_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Body'
type MockSdkClientExpandRequestInterface_Body_Call struct {
	*mock.Call
}

// Body is a helper method to define mock.On call
//   - body client.ClientExpandRequest
func (_e *MockSdkClientExpandRequestInterface_Expecter) Body(body interface{}) *MockSdkClientExpandRequestInterface_Body_Call {
	return &MockSdkClientExpandRequestInterface_Body_Call{Call: _e.mock.On("Body", body)}
}

func (_c *MockSdkClientExpandRequestInterface_Body_Call) Run(run func(body client.ClientExpandRequest)) *MockSdkClientExpandRequestInterface_Body_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.ClientExpandRequest))
	})
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_Body_Call) Return(_a0 client.SdkClientExpandRequestInterface) *MockSdkClientExpandRequestInterface_Body_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_Body_Call) RunAndReturn(run func(client.ClientExpandRequest) client.SdkClientExpandRequestInterface) *MockSdkClientExpandRequestInterface_Body_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields:
func (_m *MockSdkClientExpandRequestInterface) Execute() (*openfga.ExpandResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *openfga.ExpandResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*openfga.ExpandResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *openfga.ExpandResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openfga.ExpandResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSdkClientExpandRequestInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSdkClientExpandRequestInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockSdkClientExpandRequestInterface_Expecter) Execute() *MockSdkClientExpandRequestInterface_Execute_Call {
	return &MockSdkClientExpandRequestInterface_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockSdkClientExpandRequestInterface_Execute_Call) Run(run func()) *MockSdkClientExpandRequestInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_Execute_Call) Return(_a0 *openfga.ExpandResponse, _a1 error) *MockSdkClientExpandRequestInterface_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_Execute_Call) RunAndReturn(run func() (*openfga.ExpandResponse, error)) *MockSdkClientExpandRequestInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorizationModelIdOverride provides a mock function with given fields:
func (_m *MockSdkClientExpandRequestInterface) GetAuthorizationModelIdOverride() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizationModelIdOverride")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// MockSdkClientExpandRequestInterface_GetAuthorizationModelIdOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorizationModelIdOverride'
type MockSdkClientExpandRequestInterface_GetAuthorizationModelIdOverride_Call struct {
	*mock.Call
}

// GetAuthorizationModelIdOverride is a helper method to define mock.On call
func (_e *MockSdkClientExpandRequestInterface_Expecter) GetAuthorizationModelIdOverride() *MockSdkClientExpandRequestInterface_GetAuthorizationModelIdOverride_Call {
	return &MockSdkClientExpandRequestInterface_GetAuthorizationModelIdOverride_Call{Call: _e.mock.On("GetAuthorizationModelIdOverride")}
}

func (_c *MockSdkClientExpandRequestInterface_GetAuthorizationModelIdOverride_Call) Run(run func()) *MockSdkClientExpandRequestInterface_GetAuthorizationModelIdOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_GetAuthorizationModelIdOverride_Call) Return(_a0 *string) *MockSdkClientExpandRequestInterface_GetAuthorizationModelIdOverride_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_GetAuthorizationModelIdOverride_Call) RunAndReturn(run func() *string) *MockSdkClientExpandRequestInterface_GetAuthorizationModelIdOverride_Call {
	_c.Call.Return(run)
	return _c
}

// GetBody provides a mock function with given fields:
func (_m *MockSdkClientExpandRequestInterface) GetBody() *client.ClientExpandRequest {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBody")
	}

	var r0 *client.ClientExpandRequest
	if rf, ok := ret.Get(0).(func() *client.ClientExpandRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ClientExpandRequest)
		}
	}

	return r0
}

// MockSdkClientExpandRequestInterface_GetBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBody'
type MockSdkClientExpandRequestInterface_GetBody_Call struct {
	*mock.Call
}

// GetBody is a helper method to define mock.On call
func (_e *MockSdkClientExpandRequestInterface_Expecter) GetBody() *MockSdkClientExpandRequestInterface_GetBody_Call {
	return &MockSdkClientExpandRequestInterface_GetBody_Call{Call: _e.mock.On("GetBody")}
}

func (_c *MockSdkClientExpandRequestInterface_GetBody_Call) Run(run func()) *MockSdkClientExpandRequestInterface_GetBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_GetBody_Call) Return(_a0 *client.ClientExpandRequest) *MockSdkClientExpandRequestInterface_GetBody_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_GetBody_Call) RunAndReturn(run func() *client.ClientExpandRequest) *MockSdkClientExpandRequestInterface_GetBody_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function with given fields:
func (_m *MockSdkClientExpandRequestInterface) GetContext() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockSdkClientExpandRequestInterface_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockSdkClientExpandRequestInterface_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *MockSdkClientExpandRequestInterface_Expecter) GetContext() *MockSdkClientExpandRequestInterface_GetContext_Call {
	return &MockSdkClientExpandRequestInterface_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *MockSdkClientExpandRequestInterface_GetContext_Call) Run(run func()) *MockSdkClientExpandRequestInterface_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_GetContext_Call) Return(_a0 context.Context) *MockSdkClientExpandRequestInterface_GetContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_GetContext_Call) RunAndReturn(run func() context.Context) *MockSdkClientExpandRequestInterface_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetOptions provides a mock function with given fields:
func (_m *MockSdkClientExpandRequestInterface) GetOptions() *client.ClientExpandOptions {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOptions")
	}

	var r0 *client.ClientExpandOptions
	if rf, ok := ret.Get(0).(func() *client.ClientExpandOptions); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ClientExpandOptions)
		}
	}

	return r0
}

// MockSdkClientExpandRequestInterface_GetOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOptions'
type MockSdkClientExpandRequestInterface_GetOptions_Call struct {
	*mock.Call
}

// GetOptions is a helper method to define mock.On call
func (_e *MockSdkClientExpandRequestInterface_Expecter) GetOptions() *MockSdkClientExpandRequestInterface_GetOptions_Call {
	return &MockSdkClientExpandRequestInterface_GetOptions_Call{Call: _e.mock.On("GetOptions")}
}

func (_c *MockSdkClientExpandRequestInterface_GetOptions_Call) Run(run func()) *MockSdkClientExpandRequestInterface_GetOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_GetOptions_Call) Return(_a0 *client.ClientExpandOptions) *MockSdkClientExpandRequestInterface_GetOptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_GetOptions_Call) RunAndReturn(run func() *client.ClientExpandOptions) *MockSdkClientExpandRequestInterface_GetOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetStoreIdOverride provides a mock function with given fields:
func (_m *MockSdkClientExpandRequestInterface) GetStoreIdOverride() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStoreIdOverride")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// MockSdkClientExpandRequestInterface_GetStoreIdOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStoreIdOverride'
type MockSdkClientExpandRequestInterface_GetStoreIdOverride_Call struct {
	*mock.Call
}

// GetStoreIdOverride is a helper method to define mock.On call
func (_e *MockSdkClientExpandRequestInterface_Expecter) GetStoreIdOverride() *MockSdkClientExpandRequestInterface_GetStoreIdOverride_Call {
	return &MockSdkClientExpandRequestInterface_GetStoreIdOverride_Call{Call: _e.mock.On("GetStoreIdOverride")}
}

func (_c *MockSdkClientExpandRequestInterface_GetStoreIdOverride_Call) Run(run func()) *MockSdkClientExpandRequestInterface_GetStoreIdOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_GetStoreIdOverride_Call) Return(_a0 *string) *MockSdkClientExpandRequestInterface_GetStoreIdOverride_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_GetStoreIdOverride_Call) RunAndReturn(run func() *string) *MockSdkClientExpandRequestInterface_GetStoreIdOverride_Call {
	_c.Call.Return(run)
	return _c
}

// Options provides a mock function with given fields: options
func (_m *MockSdkClientExpandRequestInterface) Options(options client.ClientExpandOptions) client.SdkClientExpandRequestInterface {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 client.SdkClientExpandRequestInterface
	if rf, ok := ret.Get(0).(func(client.ClientExpandOptions) client.SdkClientExpandRequestInterface); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SdkClientExpandRequestInterface)
		}
	}

	return r0
}

// MockSdkClientExpandRequestInterface_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type MockSdkClientExpandRequestInterface_Options_Call struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
//   - options client.ClientExpandOptions
func (_e *MockSdkClientExpandRequestInterface_Expecter) Options(options interface{}) *MockSdkClientExpandRequestInterface_Options_Call {
	return &MockSdkClientExpandRequestInterface_Options_Call{Call: _e.mock.On("Options", options)}
}

func (_c *MockSdkClientExpandRequestInterface_Options_Call) Run(run func(options client.ClientExpandOptions)) *MockSdkClientExpandRequestInterface_Options_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.ClientExpandOptions))
	})
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_Options_Call) Return(_a0 client.SdkClientExpandRequestInterface) *MockSdkClientExpandRequestInterface_Options_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientExpandRequestInterface_Options_Call) RunAndReturn(run func(client.ClientExpandOptions) client.SdkClientExpandRequestInterface) *MockSdkClientExpandRequestInterface_Options_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSdkClientExpandRequestInterface creates a new instance of MockSdkClientExpandRequestInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSdkClientExpandRequestInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSdkClientExpandRequestInterface {
	mock := &MockSdkClientExpandRequestInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
