// Code generated by mockery. DO NOT EDIT.

package client

import (
	context "context"

	client "github.com/openfga/go-sdk/client"

	mock "github.com/stretchr/testify/mock"
)

// MockSdkClientWriteRequestInterface is an autogenerated mock type for the SdkClientWriteRequestInterface type
type MockSdkClientWriteRequestInterface struct {
	mock.Mock
}

type MockSdkClientWriteRequestInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSdkClientWriteRequestInterface) EXPECT() *MockSdkClientWriteRequestInterface_Expecter {
	return &MockSdkClientWriteRequestInterface_Expecter{mock: &_m.Mock}
}

// Body provides a mock function with given fields: body
func (_m *MockSdkClientWriteRequestInterface) Body(body client.ClientWriteRequest) client.SdkClientWriteRequestInterface {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for Body")
	}

	var r0 client.SdkClientWriteRequestInterface
	if rf, ok := ret.Get(0).(func(client.ClientWriteRequest) client.SdkClientWriteRequestInterface); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SdkClientWriteRequestInterface)
		}
	}

	return r0
}

// MockSdkClientWriteRequestInterface_Body_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Body'
type MockSdkClientWriteRequestInterface_Body_Call struct {
	*mock.Call
}

// Body is a helper method to define mock.On call
//   - body client.ClientWriteRequest
func (_e *MockSdkClientWriteRequestInterface_Expecter) Body(body interface{}) *MockSdkClientWriteRequestInterface_Body_Call {
	return &MockSdkClientWriteRequestInterface_Body_Call{Call: _e.mock.On("Body", body)}
}

func (_c *MockSdkClientWriteRequestInterface_Body_Call) Run(run func(body client.ClientWriteRequest)) *MockSdkClientWriteRequestInterface_Body_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.ClientWriteRequest))
	})
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_Body_Call) Return(_a0 client.SdkClientWriteRequestInterface) *MockSdkClientWriteRequestInterface_Body_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_Body_Call) RunAndReturn(run func(client.ClientWriteRequest) client.SdkClientWriteRequestInterface) *MockSdkClientWriteRequestInterface_Body_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields:
func (_m *MockSdkClientWriteRequestInterface) Execute() (*client.ClientWriteResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *client.ClientWriteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*client.ClientWriteResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *client.ClientWriteResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ClientWriteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSdkClientWriteRequestInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSdkClientWriteRequestInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockSdkClientWriteRequestInterface_Expecter) Execute() *MockSdkClientWriteRequestInterface_Execute_Call {
	return &MockSdkClientWriteRequestInterface_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockSdkClientWriteRequestInterface_Execute_Call) Run(run func()) *MockSdkClientWriteRequestInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_Execute_Call) Return(_a0 *client.ClientWriteResponse, _a1 error) *MockSdkClientWriteRequestInterface_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_Execute_Call) RunAndReturn(run func() (*client.ClientWriteResponse, error)) *MockSdkClientWriteRequestInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorizationModelIdOverride provides a mock function with given fields:
func (_m *MockSdkClientWriteRequestInterface) GetAuthorizationModelIdOverride() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizationModelIdOverride")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// MockSdkClientWriteRequestInterface_GetAuthorizationModelIdOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorizationModelIdOverride'
type MockSdkClientWriteRequestInterface_GetAuthorizationModelIdOverride_Call struct {
	*mock.Call
}

// GetAuthorizationModelIdOverride is a helper method to define mock.On call
func (_e *MockSdkClientWriteRequestInterface_Expecter) GetAuthorizationModelIdOverride() *MockSdkClientWriteRequestInterface_GetAuthorizationModelIdOverride_Call {
	return &MockSdkClientWriteRequestInterface_GetAuthorizationModelIdOverride_Call{Call: _e.mock.On("GetAuthorizationModelIdOverride")}
}

func (_c *MockSdkClientWriteRequestInterface_GetAuthorizationModelIdOverride_Call) Run(run func()) *MockSdkClientWriteRequestInterface_GetAuthorizationModelIdOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_GetAuthorizationModelIdOverride_Call) Return(_a0 *string) *MockSdkClientWriteRequestInterface_GetAuthorizationModelIdOverride_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_GetAuthorizationModelIdOverride_Call) RunAndReturn(run func() *string) *MockSdkClientWriteRequestInterface_GetAuthorizationModelIdOverride_Call {
	_c.Call.Return(run)
	return _c
}

// GetBody provides a mock function with given fields:
func (_m *MockSdkClientWriteRequestInterface) GetBody() *client.ClientWriteRequest {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBody")
	}

	var r0 *client.ClientWriteRequest
	if rf, ok := ret.Get(0).(func() *client.ClientWriteRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ClientWriteRequest)
		}
	}

	return r0
}

// MockSdkClientWriteRequestInterface_GetBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBody'
type MockSdkClientWriteRequestInterface_GetBody_Call struct {
	*mock.Call
}

// GetBody is a helper method to define mock.On call
func (_e *MockSdkClientWriteRequestInterface_Expecter) GetBody() *MockSdkClientWriteRequestInterface_GetBody_Call {
	return &MockSdkClientWriteRequestInterface_GetBody_Call{Call: _e.mock.On("GetBody")}
}

func (_c *MockSdkClientWriteRequestInterface_GetBody_Call) Run(run func()) *MockSdkClientWriteRequestInterface_GetBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_GetBody_Call) Return(_a0 *client.ClientWriteRequest) *MockSdkClientWriteRequestInterface_GetBody_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_GetBody_Call) RunAndReturn(run func() *client.ClientWriteRequest) *MockSdkClientWriteRequestInterface_GetBody_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function with given fields:
func (_m *MockSdkClientWriteRequestInterface) GetContext() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockSdkClientWriteRequestInterface_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockSdkClientWriteRequestInterface_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *MockSdkClientWriteRequestInterface_Expecter) GetContext() *MockSdkClientWriteRequestInterface_GetContext_Call {
	return &MockSdkClientWriteRequestInterface_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *MockSdkClientWriteRequestInterface_GetContext_Call) Run(run func()) *MockSdkClientWriteRequestInterface_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_GetContext_Call) Return(_a0 context.Context) *MockSdkClientWriteRequestInterface_GetContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_GetContext_Call) RunAndReturn(run func() context.Context) *MockSdkClientWriteRequestInterface_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetOptions provides a mock function with given fields:
func (_m *MockSdkClientWriteRequestInterface) GetOptions() *client.ClientWriteOptions {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOptions")
	}

	var r0 *client.ClientWriteOptions
	if rf, ok := ret.Get(0).(func() *client.ClientWriteOptions); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ClientWriteOptions)
		}
	}

	return r0
}

// MockSdkClientWriteRequestInterface_GetOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOptions'
type MockSdkClientWriteRequestInterface_GetOptions_Call struct {
	*mock.Call
}

// GetOptions is a helper method to define mock.On call
func (_e *MockSdkClientWriteRequestInterface_Expecter) GetOptions() *MockSdkClientWriteRequestInterface_GetOptions_Call {
	return &MockSdkClientWriteRequestInterface_GetOptions_Call{Call: _e.mock.On("GetOptions")}
}

func (_c *MockSdkClientWriteRequestInterface_GetOptions_Call) Run(run func()) *MockSdkClientWriteRequestInterface_GetOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_GetOptions_Call) Return(_a0 *client.ClientWriteOptions) *MockSdkClientWriteRequestInterface_GetOptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_GetOptions_Call) RunAndReturn(run func() *client.ClientWriteOptions) *MockSdkClientWriteRequestInterface_GetOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetStoreIdOverride provides a mock function with given fields:
func (_m *MockSdkClientWriteRequestInterface) GetStoreIdOverride() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStoreIdOverride")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// MockSdkClientWriteRequestInterface_GetStoreIdOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStoreIdOverride'
type MockSdkClientWriteRequestInterface_GetStoreIdOverride_Call struct {
	*mock.Call
}

// GetStoreIdOverride is a helper method to define mock.On call
func (_e *MockSdkClientWriteRequestInterface_Expecter) GetStoreIdOverride() *MockSdkClientWriteRequestInterface_GetStoreIdOverride_Call {
	return &MockSdkClientWriteRequestInterface_GetStoreIdOverride_Call{Call: _e.mock.On("GetStoreIdOverride")}
}

func (_c *MockSdkClientWriteRequestInterface_GetStoreIdOverride_Call) Run(run func()) *MockSdkClientWriteRequestInterface_GetStoreIdOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_GetStoreIdOverride_Call) Return(_a0 *string) *MockSdkClientWriteRequestInterface_GetStoreIdOverride_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_GetStoreIdOverride_Call) RunAndReturn(run func() *string) *MockSdkClientWriteRequestInterface_GetStoreIdOverride_Call {
	_c.Call.Return(run)
	return _c
}

// Options provides a mock function with given fields: options
func (_m *MockSdkClientWriteRequestInterface) Options(options client.ClientWriteOptions) client.SdkClientWriteRequestInterface {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 client.SdkClientWriteRequestInterface
	if rf, ok := ret.Get(0).(func(client.ClientWriteOptions) client.SdkClientWriteRequestInterface); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SdkClientWriteRequestInterface)
		}
	}

	return r0
}

// MockSdkClientWriteRequestInterface_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type MockSdkClientWriteRequestInterface_Options_Call struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
//   - options client.ClientWriteOptions
func (_e *MockSdkClientWriteRequestInterface_Expecter) Options(options interface{}) *MockSdkClientWriteRequestInterface_Options_Call {
	return &MockSdkClientWriteRequestInterface_Options_Call{Call: _e.mock.On("Options", options)}
}

func (_c *MockSdkClientWriteRequestInterface_Options_Call) Run(run func(options client.ClientWriteOptions)) *MockSdkClientWriteRequestInterface_Options_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.ClientWriteOptions))
	})
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_Options_Call) Return(_a0 client.SdkClientWriteRequestInterface) *MockSdkClientWriteRequestInterface_Options_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientWriteRequestInterface_Options_Call) RunAndReturn(run func(client.ClientWriteOptions) client.SdkClientWriteRequestInterface) *MockSdkClientWriteRequestInterface_Options_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSdkClientWriteRequestInterface creates a new instance of MockSdkClientWriteRequestInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSdkClientWriteRequestInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSdkClientWriteRequestInterface {
	mock := &MockSdkClientWriteRequestInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
