// Code generated by mockery. DO NOT EDIT.

package client

import (
	context "context"

	client "github.com/openfga/go-sdk/client"

	mock "github.com/stretchr/testify/mock"

	openfga "github.com/openfga/go-sdk"
)

// MockSdkClientReadAuthorizationModelsRequestInterface is an autogenerated mock type for the SdkClientReadAuthorizationModelsRequestInterface type
type MockSdkClientReadAuthorizationModelsRequestInterface struct {
	mock.Mock
}

type MockSdkClientReadAuthorizationModelsRequestInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSdkClientReadAuthorizationModelsRequestInterface) EXPECT() *MockSdkClientReadAuthorizationModelsRequestInterface_Expecter {
	return &MockSdkClientReadAuthorizationModelsRequestInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields:
func (_m *MockSdkClientReadAuthorizationModelsRequestInterface) Execute() (*openfga.ReadAuthorizationModelsResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *openfga.ReadAuthorizationModelsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*openfga.ReadAuthorizationModelsResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *openfga.ReadAuthorizationModelsResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openfga.ReadAuthorizationModelsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSdkClientReadAuthorizationModelsRequestInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSdkClientReadAuthorizationModelsRequestInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockSdkClientReadAuthorizationModelsRequestInterface_Expecter) Execute() *MockSdkClientReadAuthorizationModelsRequestInterface_Execute_Call {
	return &MockSdkClientReadAuthorizationModelsRequestInterface_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_Execute_Call) Run(run func()) *MockSdkClientReadAuthorizationModelsRequestInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_Execute_Call) Return(_a0 *openfga.ReadAuthorizationModelsResponse, _a1 error) *MockSdkClientReadAuthorizationModelsRequestInterface_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_Execute_Call) RunAndReturn(run func() (*openfga.ReadAuthorizationModelsResponse, error)) *MockSdkClientReadAuthorizationModelsRequestInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function with given fields:
func (_m *MockSdkClientReadAuthorizationModelsRequestInterface) GetContext() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockSdkClientReadAuthorizationModelsRequestInterface_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockSdkClientReadAuthorizationModelsRequestInterface_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *MockSdkClientReadAuthorizationModelsRequestInterface_Expecter) GetContext() *MockSdkClientReadAuthorizationModelsRequestInterface_GetContext_Call {
	return &MockSdkClientReadAuthorizationModelsRequestInterface_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_GetContext_Call) Run(run func()) *MockSdkClientReadAuthorizationModelsRequestInterface_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_GetContext_Call) Return(_a0 context.Context) *MockSdkClientReadAuthorizationModelsRequestInterface_GetContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_GetContext_Call) RunAndReturn(run func() context.Context) *MockSdkClientReadAuthorizationModelsRequestInterface_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetOptions provides a mock function with given fields:
func (_m *MockSdkClientReadAuthorizationModelsRequestInterface) GetOptions() *client.ClientReadAuthorizationModelsOptions {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOptions")
	}

	var r0 *client.ClientReadAuthorizationModelsOptions
	if rf, ok := ret.Get(0).(func() *client.ClientReadAuthorizationModelsOptions); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ClientReadAuthorizationModelsOptions)
		}
	}

	return r0
}

// MockSdkClientReadAuthorizationModelsRequestInterface_GetOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOptions'
type MockSdkClientReadAuthorizationModelsRequestInterface_GetOptions_Call struct {
	*mock.Call
}

// GetOptions is a helper method to define mock.On call
func (_e *MockSdkClientReadAuthorizationModelsRequestInterface_Expecter) GetOptions() *MockSdkClientReadAuthorizationModelsRequestInterface_GetOptions_Call {
	return &MockSdkClientReadAuthorizationModelsRequestInterface_GetOptions_Call{Call: _e.mock.On("GetOptions")}
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_GetOptions_Call) Run(run func()) *MockSdkClientReadAuthorizationModelsRequestInterface_GetOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_GetOptions_Call) Return(_a0 *client.ClientReadAuthorizationModelsOptions) *MockSdkClientReadAuthorizationModelsRequestInterface_GetOptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_GetOptions_Call) RunAndReturn(run func() *client.ClientReadAuthorizationModelsOptions) *MockSdkClientReadAuthorizationModelsRequestInterface_GetOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetStoreIdOverride provides a mock function with given fields:
func (_m *MockSdkClientReadAuthorizationModelsRequestInterface) GetStoreIdOverride() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStoreIdOverride")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// MockSdkClientReadAuthorizationModelsRequestInterface_GetStoreIdOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStoreIdOverride'
type MockSdkClientReadAuthorizationModelsRequestInterface_GetStoreIdOverride_Call struct {
	*mock.Call
}

// GetStoreIdOverride is a helper method to define mock.On call
func (_e *MockSdkClientReadAuthorizationModelsRequestInterface_Expecter) GetStoreIdOverride() *MockSdkClientReadAuthorizationModelsRequestInterface_GetStoreIdOverride_Call {
	return &MockSdkClientReadAuthorizationModelsRequestInterface_GetStoreIdOverride_Call{Call: _e.mock.On("GetStoreIdOverride")}
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_GetStoreIdOverride_Call) Run(run func()) *MockSdkClientReadAuthorizationModelsRequestInterface_GetStoreIdOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_GetStoreIdOverride_Call) Return(_a0 *string) *MockSdkClientReadAuthorizationModelsRequestInterface_GetStoreIdOverride_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_GetStoreIdOverride_Call) RunAndReturn(run func() *string) *MockSdkClientReadAuthorizationModelsRequestInterface_GetStoreIdOverride_Call {
	_c.Call.Return(run)
	return _c
}

// Options provides a mock function with given fields: options
func (_m *MockSdkClientReadAuthorizationModelsRequestInterface) Options(options client.ClientReadAuthorizationModelsOptions) client.SdkClientReadAuthorizationModelsRequestInterface {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 client.SdkClientReadAuthorizationModelsRequestInterface
	if rf, ok := ret.Get(0).(func(client.ClientReadAuthorizationModelsOptions) client.SdkClientReadAuthorizationModelsRequestInterface); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SdkClientReadAuthorizationModelsRequestInterface)
		}
	}

	return r0
}

// MockSdkClientReadAuthorizationModelsRequestInterface_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type MockSdkClientReadAuthorizationModelsRequestInterface_Options_Call struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
//   - options client.ClientReadAuthorizationModelsOptions
func (_e *MockSdkClientReadAuthorizationModelsRequestInterface_Expecter) Options(options interface{}) *MockSdkClientReadAuthorizationModelsRequestInterface_Options_Call {
	return &MockSdkClientReadAuthorizationModelsRequestInterface_Options_Call{Call: _e.mock.On("Options", options)}
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_Options_Call) Run(run func(options client.ClientReadAuthorizationModelsOptions)) *MockSdkClientReadAuthorizationModelsRequestInterface_Options_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.ClientReadAuthorizationModelsOptions))
	})
	return _c
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_Options_Call) Return(_a0 client.SdkClientReadAuthorizationModelsRequestInterface) *MockSdkClientReadAuthorizationModelsRequestInterface_Options_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientReadAuthorizationModelsRequestInterface_Options_Call) RunAndReturn(run func(client.ClientReadAuthorizationModelsOptions) client.SdkClientReadAuthorizationModelsRequestInterface) *MockSdkClientReadAuthorizationModelsRequestInterface_Options_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSdkClientReadAuthorizationModelsRequestInterface creates a new instance of MockSdkClientReadAuthorizationModelsRequestInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSdkClientReadAuthorizationModelsRequestInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSdkClientReadAuthorizationModelsRequestInterface {
	mock := &MockSdkClientReadAuthorizationModelsRequestInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
