// Code generated by mockery. DO NOT EDIT.

package client

import (
	context "context"

	client "github.com/openfga/go-sdk/client"

	mock "github.com/stretchr/testify/mock"

	openfga "github.com/openfga/go-sdk"
)

// MockSdkClientCreateStoreRequestInterface is an autogenerated mock type for the SdkClientCreateStoreRequestInterface type
type MockSdkClientCreateStoreRequestInterface struct {
	mock.Mock
}

type MockSdkClientCreateStoreRequestInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSdkClientCreateStoreRequestInterface) EXPECT() *MockSdkClientCreateStoreRequestInterface_Expecter {
	return &MockSdkClientCreateStoreRequestInterface_Expecter{mock: &_m.Mock}
}

// Body provides a mock function with given fields: body
func (_m *MockSdkClientCreateStoreRequestInterface) Body(body client.ClientCreateStoreRequest) client.SdkClientCreateStoreRequestInterface {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for Body")
	}

	var r0 client.SdkClientCreateStoreRequestInterface
	if rf, ok := ret.Get(0).(func(client.ClientCreateStoreRequest) client.SdkClientCreateStoreRequestInterface); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SdkClientCreateStoreRequestInterface)
		}
	}

	return r0
}

// MockSdkClientCreateStoreRequestInterface_Body_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Body'
type MockSdkClientCreateStoreRequestInterface_Body_Call struct {
	*mock.Call
}

// Body is a helper method to define mock.On call
//   - body client.ClientCreateStoreRequest
func (_e *MockSdkClientCreateStoreRequestInterface_Expecter) Body(body interface{}) *MockSdkClientCreateStoreRequestInterface_Body_Call {
	return &MockSdkClientCreateStoreRequestInterface_Body_Call{Call: _e.mock.On("Body", body)}
}

func (_c *MockSdkClientCreateStoreRequestInterface_Body_Call) Run(run func(body client.ClientCreateStoreRequest)) *MockSdkClientCreateStoreRequestInterface_Body_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.ClientCreateStoreRequest))
	})
	return _c
}

func (_c *MockSdkClientCreateStoreRequestInterface_Body_Call) Return(_a0 client.SdkClientCreateStoreRequestInterface) *MockSdkClientCreateStoreRequestInterface_Body_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientCreateStoreRequestInterface_Body_Call) RunAndReturn(run func(client.ClientCreateStoreRequest) client.SdkClientCreateStoreRequestInterface) *MockSdkClientCreateStoreRequestInterface_Body_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields:
func (_m *MockSdkClientCreateStoreRequestInterface) Execute() (*openfga.CreateStoreResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *openfga.CreateStoreResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*openfga.CreateStoreResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *openfga.CreateStoreResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openfga.CreateStoreResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSdkClientCreateStoreRequestInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSdkClientCreateStoreRequestInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockSdkClientCreateStoreRequestInterface_Expecter) Execute() *MockSdkClientCreateStoreRequestInterface_Execute_Call {
	return &MockSdkClientCreateStoreRequestInterface_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockSdkClientCreateStoreRequestInterface_Execute_Call) Run(run func()) *MockSdkClientCreateStoreRequestInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientCreateStoreRequestInterface_Execute_Call) Return(_a0 *openfga.CreateStoreResponse, _a1 error) *MockSdkClientCreateStoreRequestInterface_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSdkClientCreateStoreRequestInterface_Execute_Call) RunAndReturn(run func() (*openfga.CreateStoreResponse, error)) *MockSdkClientCreateStoreRequestInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetBody provides a mock function with given fields:
func (_m *MockSdkClientCreateStoreRequestInterface) GetBody() *client.ClientCreateStoreRequest {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBody")
	}

	var r0 *client.ClientCreateStoreRequest
	if rf, ok := ret.Get(0).(func() *client.ClientCreateStoreRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ClientCreateStoreRequest)
		}
	}

	return r0
}

// MockSdkClientCreateStoreRequestInterface_GetBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBody'
type MockSdkClientCreateStoreRequestInterface_GetBody_Call struct {
	*mock.Call
}

// GetBody is a helper method to define mock.On call
func (_e *MockSdkClientCreateStoreRequestInterface_Expecter) GetBody() *MockSdkClientCreateStoreRequestInterface_GetBody_Call {
	return &MockSdkClientCreateStoreRequestInterface_GetBody_Call{Call: _e.mock.On("GetBody")}
}

func (_c *MockSdkClientCreateStoreRequestInterface_GetBody_Call) Run(run func()) *MockSdkClientCreateStoreRequestInterface_GetBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientCreateStoreRequestInterface_GetBody_Call) Return(_a0 *client.ClientCreateStoreRequest) *MockSdkClientCreateStoreRequestInterface_GetBody_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientCreateStoreRequestInterface_GetBody_Call) RunAndReturn(run func() *client.ClientCreateStoreRequest) *MockSdkClientCreateStoreRequestInterface_GetBody_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function with given fields:
func (_m *MockSdkClientCreateStoreRequestInterface) GetContext() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockSdkClientCreateStoreRequestInterface_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockSdkClientCreateStoreRequestInterface_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *MockSdkClientCreateStoreRequestInterface_Expecter) GetContext() *MockSdkClientCreateStoreRequestInterface_GetContext_Call {
	return &MockSdkClientCreateStoreRequestInterface_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *MockSdkClientCreateStoreRequestInterface_GetContext_Call) Run(run func()) *MockSdkClientCreateStoreRequestInterface_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientCreateStoreRequestInterface_GetContext_Call) Return(_a0 context.Context) *MockSdkClientCreateStoreRequestInterface_GetContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientCreateStoreRequestInterface_GetContext_Call) RunAndReturn(run func() context.Context) *MockSdkClientCreateStoreRequestInterface_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetOptions provides a mock function with given fields:
func (_m *MockSdkClientCreateStoreRequestInterface) GetOptions() *client.ClientCreateStoreOptions {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOptions")
	}

	var r0 *client.ClientCreateStoreOptions
	if rf, ok := ret.Get(0).(func() *client.ClientCreateStoreOptions); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ClientCreateStoreOptions)
		}
	}

	return r0
}

// MockSdkClientCreateStoreRequestInterface_GetOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOptions'
type MockSdkClientCreateStoreRequestInterface_GetOptions_Call struct {
	*mock.Call
}

// GetOptions is a helper method to define mock.On call
func (_e *MockSdkClientCreateStoreRequestInterface_Expecter) GetOptions() *MockSdkClientCreateStoreRequestInterface_GetOptions_Call {
	return &MockSdkClientCreateStoreRequestInterface_GetOptions_Call{Call: _e.mock.On("GetOptions")}
}

func (_c *MockSdkClientCreateStoreRequestInterface_GetOptions_Call) Run(run func()) *MockSdkClientCreateStoreRequestInterface_GetOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSdkClientCreateStoreRequestInterface_GetOptions_Call) Return(_a0 *client.ClientCreateStoreOptions) *MockSdkClientCreateStoreRequestInterface_GetOptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientCreateStoreRequestInterface_GetOptions_Call) RunAndReturn(run func() *client.ClientCreateStoreOptions) *MockSdkClientCreateStoreRequestInterface_GetOptions_Call {
	_c.Call.Return(run)
	return _c
}

// Options provides a mock function with given fields: options
func (_m *MockSdkClientCreateStoreRequestInterface) Options(options client.ClientCreateStoreOptions) client.SdkClientCreateStoreRequestInterface {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 client.SdkClientCreateStoreRequestInterface
	if rf, ok := ret.Get(0).(func(client.ClientCreateStoreOptions) client.SdkClientCreateStoreRequestInterface); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SdkClientCreateStoreRequestInterface)
		}
	}

	return r0
}

// MockSdkClientCreateStoreRequestInterface_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type MockSdkClientCreateStoreRequestInterface_Options_Call struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
//   - options client.ClientCreateStoreOptions
func (_e *MockSdkClientCreateStoreRequestInterface_Expecter) Options(options interface{}) *MockSdkClientCreateStoreRequestInterface_Options_Call {
	return &MockSdkClientCreateStoreRequestInterface_Options_Call{Call: _e.mock.On("Options", options)}
}

func (_c *MockSdkClientCreateStoreRequestInterface_Options_Call) Run(run func(options client.ClientCreateStoreOptions)) *MockSdkClientCreateStoreRequestInterface_Options_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.ClientCreateStoreOptions))
	})
	return _c
}

func (_c *MockSdkClientCreateStoreRequestInterface_Options_Call) Return(_a0 client.SdkClientCreateStoreRequestInterface) *MockSdkClientCreateStoreRequestInterface_Options_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSdkClientCreateStoreRequestInterface_Options_Call) RunAndReturn(run func(client.ClientCreateStoreOptions) client.SdkClientCreateStoreRequestInterface) *MockSdkClientCreateStoreRequestInterface_Options_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSdkClientCreateStoreRequestInterface creates a new instance of MockSdkClientCreateStoreRequestInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSdkClientCreateStoreRequestInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSdkClientCreateStoreRequestInterface {
	mock := &MockSdkClientCreateStoreRequestInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
