all: false
dir: .
template: testify
pkgname: client
filename: mocks.go
packages:
  github.com/openfga/go-sdk/client:
    config:
    interfaces:
      SdkClient:
        config:
      SdkClientWriteRequestInterface:
        config:
      SdkClientReadRequestInterface:
        config:
      SdkClientListUsersRequestInterface:
        config:
      SdkClientCheckRequestInterface:
        config:
      SdkClientBatchCheckRequestInterface:
        config:
      SdkClientDeleteTuplesRequestInterface:
        config:
      SdkClientListObjectsRequestInterface:
        config:
      SdkClientReadAuthorizationModelRequestInterface:
        config:
